version: '2'

services:
  postgres:
    image: postgres
    container_name: asciinema_postgres
    restart: unless-stopped
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ### See https://hub.docker.com/_/postgres/ for more
    ### configuration options for this image.

  redis:
    image: redis
    container_name: asciinema_redis
    restart: unless-stopped
    volumes:
      - ./volumes/redis:/data
    ### See https://hub.docker.com/_/redis/ for more
    ### configuration options for this image.

  smtp:
    image: namshi/smtp
    container_name: asciinema_smtp
    restart: unless-stopped
    env_file: .env.production
    ### See https://github.com/namshi/docker-smtp for more SMTP configuration
    ### options for this image.

  nginx_asciinema:
    image: nginx:alpine
    container_name: asciinema_nginx
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nginx_asciinema"
      - "traefik.frontend.rule=Host:asciinema.mwcm.ca"
      - "traefik.docker.network=reverseproxy_reverseproxy"
    networks:
      - reverseproxy
      - default
    links:
      - phoenix
      - rails
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/asciinema.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/cache:/cache
      - ./certs:/app/priv/certs
    ### See https://hub.docker.com/_/nginx/ for more configuration options for
    ### this image.

  phoenix:
    build: .
    image: asciinema/asciinema-server:latest
    command: mix phx.server
    container_name: asciinema_phoenix
    restart: unless-stopped
    networks:
      - reverseproxy
      - default
    links:
      - redis
      - postgres
      - smtp
    env_file: .env.production
    ### Uncomment for access to ExqUI (for debugging):
    # ports:
    #   - "4040:4040"
    volumes:
      - ./uploads:/app/uploads
      - /tmp/asciinema-web:/tmp

  rails:
    build: .
    image: asciinema/asciinema-server:latest
    command: bundle exec unicorn -c config/unicorn.rb
    container_name: asciinema_rails
    restart: unless-stopped
    links:
      - redis
      - postgres
    env_file: .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./log:/app/log
      - /tmp/asciinema-web:/tmp
      - ./volumes/tmp:/app/tmp


   
networks:
   reverseproxy:
      external:
         name: reverseproxy_reverseproxy
